import clsx from 'clsx';
import type { Metadata } from 'next';
import { Red_Hat_Display } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

<body className='overflow-x-hidden'></body>;
const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(redHatDisplay.variable, `antialiased`)}>
        {children}
      </body>
    </html>
  );
}
